version: "3"
services:   
    sender:
        image: sender
        build:
            context: ./Sender/
            dockerfile: Dockerfile
        depends_on:
            - rabbitmq
    receiver:
        image: receiver
        build:
            context: ./Receiver/
            dockerfile: Dockerfile
        depends_on:
            - rabbitmq
    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
            - "15672:15672"
        healthcheck:
            test: ["CMD-SHELL", "if rabbitmqctl status; then \nexit 0 \nfi \nexit 1"]
            interval: 10s
            retries: 5